name: Main workflow to run on change to repo-identification.yaml workflow
on:
  push:
    paths:
      - 'repo-identification.yaml'
      - 'README.md'

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task for testing
        run: |
          echo "A file was changed!"
          echo "Done!!!"
