name: Workflow on change to repo-identification.yaml workflow
on:
  push:
    paths:
      - '.github/workflows/repo-identification.yaml'
  pull_request:
    paths:
      - '.github/workflows/repo-identification.yaml'

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task
        run: echo "repo-identification.yaml workflow was changed"