name: Repo Identification

on:
  push:
    paths:
      - 'repo-identification.yaml'
      - '.github/CODEOWNERS'

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task for testing
        run: |
          echo "This workflow was changed."
